#DataSource Config
spring:
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    datasource:
        url: jdbc:mysql://localhost:3306/shiro_test_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver

server:
    port: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

blog:
    jwt:
        # 加密秘钥
        secret: f4e2e52034348f86b67cde581c0f9eb5
        # token有效时长，7天，单位秒
        expire: 604800
        header: token
